Ap_Vouch = {
    'av.cLink':"联结号",
    'av.cVouchType':"单据类型编码",
    'av.cVouchID':"单据编号",
    'av.cVouchID1':"对应单据号",
    'av.dVouchDate':"单据日期",
    'av.cDwCode':"单位编码",
    'av.cDeptCode':"部门编码",
    'av.cPerson':"业务员编码",
    'av.cItem_Class':"项目大类编码",
    'av.cItemCode':"项目编码",
    'av.cDigest':"摘要",
    'av.cCode':"科目编码",
    'av.cexch_name':"币种名称",
    'av.iExchRate':"汇率",
    'av.bd_c':"借贷方向",
    'av.iAmount':"本币金额",
    'av.iAmount_f':"原币金额",
    'av.iRAmount':"本币余额",
    'av.iRAmount_f':"原币余额",
    'av.cPayCode':"付款条件编码",
    'av.cOperator':"录入人",
    'av.cCheckMan':"审核人",
    'av.cCoVouchType':"对应单据类型",
    'av.cDestNo':"去向号码",
    'av.cSrcNo':"来源号码",
    'av.bStartFlag':"期初标志",
    'av.cPZid':"凭证线索号",
    'av.cFlag':"应收应付标志",
#     'av.cDefine1':"自定义项1",
#     'av.cDefine2':"自定义项2",
#     'av.cDefine3':"自定义项3",
#     'av.cDefine4':"自定义项4",
#     'av.cDefine5':"自定义项5",
#     'av.cDefine6':"自定义项6",
#     'av.cDefine7':"自定义项7",
#     'av.cDefine8':"自定义项8",
#     'av.cDefine9':"自定义项9",
#     'av.cDefine10':"自定义项10",
    'av.iAmount_s':"数量",
    'av.iRAmount_s':"数量余额",
    'av.VT_ID':"单据模版号",
    'av.Ufts':"时间戳",
    'av.iClosesID':"结算单子表标识",
    'av.iCoClosesID':"对应结算单子表标识",
#     'av.cDefine11':"自定义项11",
#     'av.cDefine12':"自定义项12",
#     'av.cDefine13':"自定义项13",
#     'av.cDefine14':"自定义项14",
#     'av.cDefine15':"自定义项15",
#     'av.cDefine16':"自定义项16",
    'av.cItemName':"项目名称",
    'av.cGatheringPlan':"收付款协议",
    'av.dCreditStart':"立账日",
    'av.iCreditPeriod':"账期",
    'av.dGatheringDate':"到期日",
    'av.dcreatesystime':"制单时间",
    'av.dverifysystime':"审核时间",
    'av.dmodifysystime':"修改时间",
    'av.cmodifier':"修改人",
    'av.dmoddate':"修改日期",
    'av.dverifydate':"审核日期",
    'av.Auto_ID':"自动编号",
#     'av.cPZNum':"cPZNum",
#     'av.doutbilldate':"doutbilldate",
#     'av.iPrintCount':"iPrintCount",
#     'av.cPluginsourcetype':"cPluginsourcetype",
#     'av.iPluginsourceautoid':"iPluginsourceautoid",
#     'av.cPluginsourceautoid':"cPluginsourceautoid",
#     'av.iBusType':"iBusType",
#     'av.cagentcuscode':"cagentcuscode",
#     'av.cOrderNo':"cOrderNo",
#     'av.cContractType':"cContractType",
#     'av.iSource':"iSource",
#     'av.cContractID':"cContractID"
}