Code = {
    'c.i_id':"自动编号",
    'c.cclass':"科目类型",
    'c.cclass_engl':"科目类型英文名称",
    'c.cclassany':"财务分析类型",
    'c.cclassany_engl':"财务分析类型英文名称",
    'c.ccode':"科目编码",
    'c.ccode_name':"科目名称",
    'c.ccode_engl':"科目英文名称",
    'c.igrade':"编码级次",
    'c.bproperty':"科目性质",
    'c.cbook_type':"账页格式",
    'c.cbook_type_engl':"账页格式英文名称",
    'c.chelp':"科目助记码",
    'c.cexch_name':"币种名称",
    'c.cmeasure':"计量单位",
    'c.bperson':"是否个人往来核算",
    'c.bcus':"是否客户往来核算",
    'c.bsup':"是否供应商往来核算",
    'c.bdept':"是否部门核算",
    'c.bitem':"是否项目核算",
    'c.cass_item':"项目大类编码",
    'c.br':"是否日记账",
    'c.be':"是否银行账",
    'c.cgather':"是否汇总打印",
    'c.bend':"是否末级",
    'c.bexchange':"是否参与汇兑损益计算",
    'c.bcash':"是否现金科目",
    'c.bbank':"是否银行科目",
    'c.bused':"银行账科目是否启用",
    'c.bd_c':"银行账科目对账方向",
    'c.dbegin':"银行账科目启用日期",
    'c.dend':"银行账科目对账截止日期",
    'c.itrans':"特殊科目标志",
#     'c.bclose':"",
#     'c.cother':"",
#     'c.iotherused':"",
#     'c.bcDefine1':"",
#     'c.bcDefine2':"",
#     'c.bcDefine3':"",
#     'c.bcDefine4':"",
#     'c.bcDefine5':"",
#     'c.bcDefine6':"",
#     'c.bcDefine7':"",
#     'c.bcDefine8':"",
#     'c.bcDefine9':"",
#     'c.bcDefine10':"",
#     'c.iViewItem':"",
#     'c.bGCJS':"",
#     'c.bCashItem':"",
#     'c.pubufts':"",
#     'c.bcDefine11':"",
#     'c.bcDefine12':"",
#     'c.bcDefine13':"",
#     'c.bcDefine14':"",
#     'c.bcDefine15':"",
#     'c.bcDefine16':"",
#     'c.bReport':"",
#     'c.cUserDefineType':"",
#     'c.iyear:""
}